apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-pods
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["pods", "deployments"]
  verbs: ["get", "set", "patch", "watch", "list"]